# Project: Project1
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = LALLA.o $(RES)
LINKOBJ  = LALLA.o $(RES)
LIBS =  -L"C:/Users/luisa/OneDrive/Documents/HTML/Devfiles/Dev-Cpp/lib"  
INCS =  -I"C:/Users/luisa/OneDrive/Documents/HTML/Devfiles/Dev-Cpp/include" 
CXXINCS =  -I"C:/Users/luisa/OneDrive/Documents/HTML/Devfiles/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Users/luisa/OneDrive/Documents/HTML/Devfiles/Dev-Cpp/include/c++/3.4.2/backward"  -I"C:/Users/luisa/OneDrive/Documents/HTML/Devfiles/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"C:/Users/luisa/OneDrive/Documents/HTML/Devfiles/Dev-Cpp/include/c++/3.4.2"  -I"C:/Users/luisa/OneDrive/Documents/HTML/Devfiles/Dev-Cpp/include" 
BIN  = LALA.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before LALA.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "LALA.exe" $(LIBS)

LALLA.o: LALLA.cpp
	$(CPP) -c LALLA.cpp -o LALLA.o $(CXXFLAGS)
